name = "pHcalc"
uuid = "a110ef22-8a98-4da7-b9d8-cfb8dc232cf9"
authors = ["Eduardo Gonik <gonik@quimica.unlp.edu.ar>"]
version = "0.1.0"

[deps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
